### PR TITLE
Feature: New update_model_rule

### PR DESCRIPTION
**Pull request by buixuankhai1204**
Hi @GoranBrkuljan! I want to add a new update_model_rule for updating dynamic fields of struct by primary key. Hope you check my PR. Thank you!

example: 

Screenshot 2024-09-11 164039

### CODE REVIEW

**Comment by GoranBrkuljan** [comment]
@buixuankhai1204 are you sure we need this? The thing is that we can set fields to partial model itself and do update which will make sure that fields are in correct order.

```rust
partial_user!(UpdateUsernameUser, id, username, updated_at);

UpdateUsernameUser {
      id,
      username: 'updated_username'.to_string(),
      updated_at: Utc::now(),
  }
  .update()
  .execute(db_session)
  .await?;
```

And for special cases like in counter tables where we have increments and decrements, we have helper functions e.g.
`model.increment_<counter_field>(1).execute(db)`

**Comment by buixuankhai1204** [comment]
Yes, i understand this case. but this case must create new struct for update behavior, and by this way more expensive than my option.
And another reason use this code to  take advantage of query statement on IDE, very clearly.

anw, it just an another way to update. Thanks @GoranBrkuljan

**Comment by GoranBrkuljan** [comment]
Thank you for the PR. I truly appreciate it when someone raises a PR and takes actionable steps upon facing an issue.

However, I would not encourage this approach as it is very implicit and users can easily misplace arguments for primary keys and other fields. Also, there should be no performance differences in using a struct compared to providing a tuple for the query itself, as you proposed. But a struct-based approach is way easier because we have explicit fields and the query in the background will use the correct field order.

For `find` and `delete` queries, we have something similar, but there we only provide the `where` clause, and we have it in case we want to use range operators for clustering keys (`>`, `<`, `<=`, `>=`). However, range operators are not supported by update queries, so this could further confuse users as they would provide a `set` clause here.

**Comment by buixuankhai1204** [comment]
Okay, thanks @GoranBrkuljan. I got it.

**Pull request closed without merging**
