### PR TITLE
fix: add escape characters for all binds

### PR DESCRIPTION
**Pull request by dracarys18**

### CODE REVIEW

**Comment by dracarys18** [comment]
@GoranBrkuljan Lemme know if you need the changes any place else

**Comment by GoranBrkuljan** [comment]
@dracarys18 we need in our migration lib

`charybdis-migrate/src/model/runner.rs`

**Comment by GoranBrkuljan** [comment]
Hey @dracarys18, this is still incomplete as we need to update all queries in migration runner.rs. Also tbh, I don't know if we should support this. 'Token' might be the only reserved keyword that could be used for column name, and having this logic could introduce bugs and maintenance overhead that simply is not worth it.

**Comment by dracarys18** [comment]
@GoranBrkuljan I don't think there will be any chances of bugs on this. Afaik this is a common practice among ORM's to escape to add escape characters to the column names. But if you feel you don't need it feel free to close the PR

**Comment by GoranBrkuljan** [comment]
@dracarys18 I agree that it's standard practice among typical ORM's to do that. However, ScyllaDB is not the standard DB, and this is not an standard ORM. To achieve high performance with easy-to-use API, we relay heavily on procedurals macros, so we should try to keep other things as simple as possible. We also have complicated migration logic that scans diffs between model definition and DB to run migration, so we have a lot of migration queries. Also, it's generally advisable to avoid this practice so we can prevent syntax errors and other potential pitfalls.

Thanks for the PR, but for now I think it's just easier if we use 'user_token' or similar wording for column names. 

Cheers!

**Comment by GoranBrkuljan** [comment]
Note that in future we can implement this with field attribute 'escape' e.g. 

```rust
#[charybdis_model(..)]
struct User {
    id: Uuid,
    
    #charybdis[escape]
    token: Text,
}
```

So it's field specific for those who need it.

**Pull request closed without merging**
